name = "claude-code-ui"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:pages"

[pages]
pages_build_output_dir = "dist"
pages_build_command = "npm run build:pages"

[functions]
directory = "functions"