name = "claude-code-ui"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:pages"

[pages]
pages_build_output_dir = "dist"

# SSL and Security Settings
[pages.environment.production]
name = "production"

[pages.environment.preview]
name = "preview"